server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{ip-address-vm-loki}:3100/loki/api/v1/push

scrape_configs:

 - job_name: syslog
   static_configs:
   - targets:
      - localhost
     labels:
      host: {hostname-vm}
      job: syslog  # A job label is fairly standard in prometheus and useful for linking metrics and logs.
      __path__: /var/log/syslog

 - job_name: authlog
   static_configs:
   - targets:
      - localhost
     labels:
      host: {hostname-vm}
      job: authlog # A job label is fairly standard in prometheus and useful for linking metrics and logs.
      __path__: /var/log/auth.log

 - job_name: kernelLog
   static_configs:
   - targets:
      - localhost
     labels:
      host: {hostname-vm}
      job: KernelLog # A job label is fairly standard in prometheus and useful for linking metrics and logs.
      __path__: /var/log/kern.log
