{
 "title": "Loki - Syslog",
 "description": "An example dashboard showing Loki ingested syslogs forwarded from syslog-ng. Part of my Loki Syslog All In One project.",
 "tags": [ "syslog" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(job=\"syslog\", host)"
   },
   {
    "name": "filter",
    "label": "Filter",
    "query": "info,debug,warn,error,ERR,DNS,auth_failures,wpa_auth_failures,no path available"
   },
   { "name": "free_form_filter", "label": "Free Form Filter" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "Log Line Counts By Host (Unfiltered)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Counts By Host ($host) - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=~\"$host\", job=\"syslog\"} [$__interval] |~ \"$free_form_filter\" |~ \"$filter\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Logs By Host - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=~\"$host\"} |~ \"$free_form_filter\" |~ \"$filter\""
    }
   ]
  },
  {
   "title": "Critical in syslog alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}|~ \"critical|crit|Critical|CRITICAL\"[1m])"
    }
   ]
  },
  {
   "title": "Alert in syslog alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}|~ \"alert|Alert|ALERT\"[1m])"
    }
   ]
  },
  {
   "title": "Warning in syslog alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}|~ \"warning|warn|Warning|WARNING\"[1m])"
    }
   ]
  },
  {
   "title": "Error in syslog alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}|~ \"error|err|Error|ERROR\"[1m])"
    }
   ]
  }
 ]
}