{
 "title": "Loki - authlog",
 "description": "An example dashboard showing Loki ingested authlogs forwarded from authlog-ng. Part of my Loki authlog All In One project.",
 "tags": [ "authlog" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(job=\"authlog\", host)"
   },
   {
    "name": "filter",
    "label": "Filter",
    "query": "fail,failure,Failure,Failed,error,ERR,auth_failures,wpa_auth_failures"
   },
   { "name": "free_form_filter", "label": "Free Form Filter" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "Log Line Counts By Host (Unfiltered)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"authlog\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Counts By Host ($host) - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=~\"$host\", job=\"authlog\"} [$__interval] |~ \"$free_form_filter\" |~ \"$filter\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Failled Login Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"authlog\"}|~ \"Failed password|Failed|failed|Failure|failure|authentication failure\"[1m])"
    }
   ]
  },
  {
   "title": "Logs By Host - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"authlog\", host=~\"$host\"} |~ \"$free_form_filter\" |~ \"$filter\""
    }
   ]
  }
 ]
}